services:
  - type: web
    name: todo-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://karthik:1234@cluster0.pgvpg.mongodb.net/"
